import { NextRequest, NextResponse } from 'next/server';
import { saveProgramToDb } from '@/lib/store';

export async function POST(request: NextRequest) {
  try {
    const { plan_data, program_name = 'My Squad Plan', description = 'Generated by AI' } = await request.json();
    const programId = saveProgramToDb(program_name, description, plan_data);
    return NextResponse.json({ status: 'success', program_id: programId });
  } catch (error: any) {
    return NextResponse.json({ detail: error.message }, { status: 500 });
  }
}
